---

name: ci
on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: check out repository
        uses: actions/checkout@v2

      - name: setup python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: "3.6"

      - name: setup python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: install tox
        run: pip install tox

      - name: run build tasks
        run: tox
